### ISSUE TITLE
UnsolvedSymbolException

### ISSUE THREAD

**Issue by AhmedSalihCezayir** [aiddroid/java-callgraph#1]
Hello. When I run the code, I get an UnsolvedSymbolException. I have the following classes.

### Main.java
`public class Main{
    public static void main(String[] args) {
        School school = new School();
        school.big_func();
    }
}`

### School.java
`
public class School {
    StudentX studentA;

    public School(){
        studentA = new StudentX("Ahmed", 20, "Computer Science");
    }

    public void big_func(){
        studentA.say_name();
        studentA.say_age();
        studentA.info_dump();
    }
}`

### Student.java
`
public class StudentX extends PersonX {
    public String major;

    public StudentX(String name, int age, String major){
        super(name, age);
        this.major = major;
    }

    @Override
    public void say_name(){
        System.out.println("My name is " + name);
    }

    public void info_dump_different(){
        say_name();
        say_age();
        System.out.println("Thats all");
    }
}`

### PersonX.java
`
public class PersonX {
    public String name;
    public int age;

    public PersonX(String name, int age){
        this.name = name;
        this.age = age;
    }

    public void say_name(){
        System.out.println("My name is " + name);
    }

    public void say_age(){
        System.out.println("My age is " + age);
    }

    public void info_dump(){
        say_name();
        say_age();
        System.out.println("Thats all");
    }
}
` 

These classes are in a directory called "code" and my project structure is like below:
- project folder
     - code folder
     - java-callgraph-1.0-SNAPSHOT-jar-with-dependencies.jar

To run the code, I use the following command:
        java -jar java-callgraph-1.0-SNAPSHOT-jar-with-dependencies.jar -s code -o output

I would appreciate any help.

**Comment by AhmedSalihCezayir** [comment]
Sorry for the messy code blocks. I don't know why they are like that. I could not make them normal.

**Comment by aiddroid** [comment]
> 

Maybe you should upgrade to JDK 15
